# Generated by Django 4.2.9 on 2024-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='samedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
