# Generated by Django 4.2.9 on 2024-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_data_samedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='samedata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='samedata',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
