# Generated by Django 3.2 on 2024-08-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_thirddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='forthdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
