# Generated by Django 5.1 on 2024-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0014_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
