# Generated by Django 5.1 on 2024-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0017_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
